bounding-box:
  corner-1:
    x: -18.5
    y: 83.5
    z: 20.5
  corner-2:
    x: 18.5
    y: 98.5
    z: 40.5
team1-spawn: 
  x: 22.5 
  y: 97.0 
  z: 30.5 
  yaw: 90.0 
  pitch: 0.0
team2-spawn: 
  x: -21.5 
  y: 97.0 
  z: 30.5 
  yaw: -90.0 
  pitch: 0.0
general-spawn: 
  x: -21.5 
  y: 97.0 
  z: 30.5 
  yaw: -90.0 
  pitch: 0.0
starting-time: 15
match-time: 60
goals-to-win: 5
team1name: RED
team2name: BLUE
death-height: 82.0


